// Admin Management
export const ADMIN_USER_LIST_REQUEST = 'ADMIN_USER_LIST_REQUEST';
export const ADMIN_USER_LIST_SUCCESS = 'ADMIN_USER_LIST_SUCCESS';
export const ADMIN_USER_LIST_FAIL = 'ADMIN_USER_LIST_FAIL';

export const ADMIN_APPLICATION_REQUEST = 'ADMIN_APPLICATION_REQUEST';
export const ADMIN_APPLICATION_SUCCESS = 'ADMIN_APPLICATION_SUCCESS';
export const ADMIN_APPLICATION_FAIL = 'ADMIN_APPLICATION_FAIL';

export const ADMIN_REVOKE_REQUEST = 'ADMIN_REVOKE_REQUEST';
export const ADMIN_REVOKE_SUCCESS = 'ADMIN_REVOKE_SUCCESS';
export const ADMIN_MANAGE_APPLICATION_REQUEST = 'ADMIN_MANAGE_APPLICATION_REQUEST';
export const ADMIN_REVOKE_USER_REQUEST = 'ADMIN_REVOKE_USER_REQUEST';
export const ADMIN_USER_DETAILS_REQUEST = 'ADMIN_USER_DETAILS_REQUEST';
export const ADMIN_REQUESTS_REQUEST = 'ADMIN_REQUESTS_REQUEST';
export const ADMIN_MANAGE_APPLICATION_SUCCESS = 'ADMIN_MANAGE_APPLICATION_SUCCESS';
export const ADMIN_REVOKE_USER_SUCCESS = 'ADMIN_REVOKE_USER_SUCCESS';
export const ADMIN_USER_DETAILS_SUCCESS = 'ADMIN_USER_DETAILS_SUCCESS';
export const ADMIN_REQUESTS_SUCCESS = 'ADMIN_REQUESTS_SUCCESS';
export const ADMIN_MANAGE_APPLICATION_FAIL = 'ADMIN_MANAGE_APPLICATION_FAIL';
export const ADMIN_REVOKE_USER_FAIL = 'ADMIN_REVOKE_USER_FAIL';
export const ADMIN_USER_DETAILS_FAIL = 'ADMIN_USER_DETAILS_FAIL';
export const ADMIN_REQUESTS_FAIL = 'ADMIN_REQUESTS_FAIL';
export const ADMIN_REVOKE_FAIL = 'ADMIN_REVOKE_FAIL';
export const ADMIN_LIST_SUCCESS = 'ADMIN_LIST_SUCCESS';
export const ADMIN_LIST_REQUEST = 'ADMIN_LIST_REQUEST';
export const ADMIN_LIST_FAIL = 'ADMIN_LIST_FAIL';
