// Canteen Item Management
export const  CANTEEN_VIEW_TRANSACTIONS_FAIL = ' CANTEEN_VIEW_TRANSACTIONS_FAIL';
export const CANTEEN_VIEW_TRANSACTIONS_SUCCESS = 'CANTEEN_VIEW_TRANSACTIONS_SUCCESS';
export const CANTEEN_VIEW_TRANSACTIONS_REQUEST = 'CANTEEN_VIEW_TRANSACTIONS_REQUEST';

export const CANTEEN_CANCEL_ORDER_FAIL = 'CANTEEN_CANCEL_ORDER_FAIL';
export const CANTEEN_CANCEL_ORDER_SUCCESS = 'CANTEEN_CANCEL_ORDER_SUCCESS';
export const CANTEEN_CANCEL_ORDER_REQUEST = 'CANTEEN_CANCEL_ORDER_REQUEST';

export const CANTEEN_ACCEPT_ORDER_FAIL = 'CANTEEN_ACCEPT_ORDER_FAIL';
export const CANTEEN_ACCEPT_ORDER_SUCCESS = 'CANTEEN_ACCEPT_ORDER_SUCCESS';
export const CANTEEN_ACCEPT_ORDER_REQUEST = 'CANTEEN_ACCEPT_ORDER_REQUEST';

export const CANTEEN_VIEW_ORDERS_FAIL = 'CANTEEN_VIEW_ORDERS_FAIL';
export const CANTEEN_VIEW_ORDERS_SUCCESS = 'CANTEEN_VIEW_ORDERS_SUCCESS';
export const CANTEEN_VIEW_ORDERS_REQUEST = 'CANTEEN_VIEW_ORDERS_REQUEST';

export const CANTEEN_DELETE_ITEM_FAIL = 'CANTEEN_DELETE_ITEM_FAIL';
export const CANTEEN_DELETE_ITEM_SUCCESS = 'CANTEEN_DELETE_ITEM_SUCCESS';
export const CCANTEEN_DELETE_ITEM_REQUESTL = 'CANTEEN_DELETE_ITEM_REQUEST';

export const  CANTEEN_UPDATE_ITEM_FAIL = ' CANTEEN_UPDATE_ITEM_FAIL';
export const CANTEEN_UPDATE_ITEM_SUCCESS = 'CANTEEN_UPDATE_ITEM_SUCCESS';
export const CANTEEN_UPDATE_ITEM_REQUEST = 'CANTEEN_UPDATE_ITEM_REQUEST';
export const CANTEEN_ADD_ITEM_FAIL = 'CANTEEN_ADD_ITEM_FAIL';
export const  CANTEEN_ADD_ITEM_SUCCESS= ' CANTEEN_ADD_ITEM_SUCCESS';
export const CANTEEN_ADD_ITEM_REQUEST = 'CANTEEN_ADD_ITEM_REQUEST';
export const CANTEEN_DELETE_ITEM_REQUEST = 'CANTEEN_DELETE_ITEM_REQUEST';
export const CANTEEN_ANALYTICS_REQUEST = 'CANTEEN_ANALYTICS_REQUEST';
export const CANTEEN_ANALYTICS_SUCCESS = 'CANTEEN_ANALYTICS_SUCCESS';
export const  CANTEEN_ANALYTICS_FAIL = ' CANTEEN_ANALYTICS_FAIL';
export const  CANTEEN_ITEM_REQUEST = ' CANTEEN_ITEM_REQUEST';
export const  CANTEEN_ITEM_SUCCESS = ' CANTEEN_ITEM_SUCCESS';
export const  CANTEEN_ITEM_FAIL = ' CANTEEN_ITEM_FAIL';
export const GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_FAIL = 'GET_ORDER_DETAILS_FAIL';
export const CANTEEN_NOTIFY_ORDER_FAIL = 'CANTEEN_NOTIFY_ORDER_FAILL';
export const CANTEEN_NOTIFY_ORDER_SUCCESS = 'CANTEEN_NOTIFY_ORDER_SUCCESS';
export const CANTEEN_NOTIFY_ORDER_REQUEST = 'CANTEEN_NOTIFY_ORDER_REQUEST';
