export const FETCH_USER_ORDERS_REQUEST= 'FETCH_USER_ORDERS_REQUEST';
export const FETCH_USER_ORDERS_SUCCESS= 'FETCH_USER_ORDERS_SUCCESS';
export const FETCH_USER_ORDERS_FAIL= 'FETCH_USER_ORDERS_FAIL';
export const ITEM_FAIL= 'ITEM_FAIL';
export const ITEM_REQUEST= 'ITEM_REQUEST';
export const ITEM_SUCCESS= 'ITEM_SUCCESS';
export const PLACE_ORDER_REQUEST = 'PLACE_ORDER_REQUEST';
export const PLACE_ORDER_SUCCESS = 'PLACE_ORDER_SUCCESS';
export const PLACE_ORDER_FAIL = 'PLACE_ORDER_FAIL';

export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAIL = 'GET_ORDER_FAIL';

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST';
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS';
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL';