// User Authentication
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_VERIFY_OTP_REQUEST = 'USER_VERIFY_OTP_REQUEST';
export const USER_VERIFY_OTP_SUCCESS = 'USER_VERIFY_OTP_SUCCESS';
export const USER_VERIFY_OTP_FAIL = 'USER_VERIFY_OTP_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const USER_ORDER_HISTORY_REQUEST = 'USER_ORDER_HISTORY_REQUEST';
export const USER_ORDER_HISTORY_SUCCESS = 'USER_ORDER_HISTORY_SUCCESS';
export const USER_ORDER_HISTORY_FAIL = 'USER_ORDER_HISTORY_FAIL';
export const GET_ORDER_HISTORY_FAIL = 'GET_ORDER_HISTORY_FAIL';
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS';
export const VERIFY_PROFILE_OTP_FAIL = 'VERIFY_PROFILE_OTP_FAIL';
export const VERIFY_PROFILE_OTP_SUCCESS = 'VERIFY_PROFILE_OTP_SUCCESS';
export const VERIFY_PROFILE_OTP_REQUEST = 'VERIFY_PROFILE_OTP_REQUEST';
export const APPLY_ADMIN_FAIL = 'APPLY_ADMIN_FAIL';
export const APPLY_ADMIN_SUCCESS = 'APPLY_ADMIN_SUCCESS';
export const GET_ORDER_HISTORY_REQUEST = 'GET_ORDER_HISTORY_SUCCESS';
export const APPLY_ADMIN_REQUEST = 'APPLY_ADMIN_REQUEST';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS= 'GET_PROFILE_SUCCESS';
export const USER_LOGOUT= 'USER_LOGOUT';
export const USER_OTP_REQUEST= 'USER_OTP_REQUEST';
export const USER_OTP_SUCCESS= 'USER_OTP_SUCCESS';
export const USER_OTP_FAIL= 'USER_OTP_FAIL';
export const CANCEL_ADMIN_FAIL= 'USER_OTP_FAIL';
export const CANCEL_ADMIN_SUCCESS= 'USER_OTP_FAIL';
export const CANCEL_ADMIN_REQUEST= 'USER_OTP_FAIL';

export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';

export const PASSWORD_RESET_CONFIRM_REQUEST = 'PASSWORD_RESET_CONFIRM_REQUEST';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const CANTEEN_ITEM_USER_FAIL= 'CANTEEN_ITEM_USER_FAIL';
export const CANTEEN_ITEM_USER_SUCCESS = 'CANTEEN_ITEM_USER_SUCCESS';
export const  CANTEEN_ITEM_USER_REQUEST = ' CANTEEN_ITEM_USER_REQUEST';
